Adjusted CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,9 +1,14 @@
 image: ruby:3.2
 
 pages:
-  script:
-    - mkdir public  
-    - cp -r * public/  
+  script: |
+    if test -f "index.html"; then  # Check for index.html in the Alaska folder
+      gem install jekyll
+      jekyll build -d public
+    else
+      echo "No index.html file found, this file is required."
+      exit 1  # Exit with a non-zero status to indicate failure
+    fi
   artifacts:
     paths:
       - public
